server:
  port: 8089

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-rest: earliest
      key-deserializer:
        org.apache.kafka.comman.serialization.StringDeserializer
      value-deserializer:
        org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.package: "*"

  mail:
    host: smtp.gmail.com
    port: 587
    username: skg@gmail.com
    password: test12345
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
twilio:
  account-sid: AC6dd4ea3d0205cebdb3af3a78692f7025
  auth-token: 90df95258f91582da0f0c250cabaf228
  from-number: +19472253236

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost://9411/api/v2/spans