server:
  port: 8089

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-rest: earliest
      key-deserializer:
        org.apache.kafka.comman.serialization.StringDeserializer
      value-deserializer:
        org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.package: "*"

  mail:
    host: smtp.gmail.com
    port: 587
    username: skg@gmail.com
    password: test12345
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
twilio:
  account-sid: US97eea9811ad2c323a13519551e8f6dda
  auth-token: 90df95258f91582da0f0c250cabaf228
